// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL19RWozhCyCLwtkapac2eFsb_WWPgEmA',
    appId: '1:715842707184:web:b07f340c0b85e755ad6c35',
    messagingSenderId: '715842707184',
    projectId: 'ledgrr-9e6fc',
    authDomain: 'ledgrr-9e6fc.firebaseapp.com',
    storageBucket: 'ledgrr-9e6fc.firebasestorage.app',
    measurementId: 'G-ZDR18SRBBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0TstGPblVHG4ln3MZV7zqP1_TQYLrnM',
    appId: '1:715842707184:android:deb16ec623a99be6ad6c35',
    messagingSenderId: '715842707184',
    projectId: 'ledgrr-9e6fc',
    storageBucket: 'ledgrr-9e6fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASX4ZGGhfZ3fNd_BKqlMsrkRVK2XdhN_A',
    appId: '1:715842707184:ios:01515cfd36474366ad6c35',
    messagingSenderId: '715842707184',
    projectId: 'ledgrr-9e6fc',
    storageBucket: 'ledgrr-9e6fc.firebasestorage.app',
    iosBundleId: 'com.example.ledgrr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASX4ZGGhfZ3fNd_BKqlMsrkRVK2XdhN_A',
    appId: '1:715842707184:ios:01515cfd36474366ad6c35',
    messagingSenderId: '715842707184',
    projectId: 'ledgrr-9e6fc',
    storageBucket: 'ledgrr-9e6fc.firebasestorage.app',
    iosBundleId: 'com.example.ledgrr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL19RWozhCyCLwtkapac2eFsb_WWPgEmA',
    appId: '1:715842707184:web:ce44c5cca41d2a62ad6c35',
    messagingSenderId: '715842707184',
    projectId: 'ledgrr-9e6fc',
    authDomain: 'ledgrr-9e6fc.firebaseapp.com',
    storageBucket: 'ledgrr-9e6fc.firebasestorage.app',
    measurementId: 'G-8JNMZD58Q4',
  );
}
